# https://github.com/marketplace/actions/close-stale-issues
# https://docs.github.com/ja/actions/use-cases-and-examples/project-management/closing-inactive-issues
name: Close stale issues
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 14
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity.'
          close-issue-message: 'This issue was closed because it has been inactive for 14 days since being marked as stale.'
          close-pr-message: 'This PR was closed because it has been inactive for 14 days since being marked as stale.'
          exempt-issue-labels: 'bug,dnc'
          exempt-pr-labels: 'bug,dnc'
          exempt-draft-pr: true
          delete-branch: true
